### PR TITLE
Arch migration

### PR DESCRIPTION
**Pull request by jjhelmus**
Build for the aarch64 and ppc64le platforms

### CODE REVIEW

**Comment by jjhelmus** [comment]
Looks like there is an issue with the Python 2.7 build on Windows.  Not sure if this is needed before merging.  If the maintainers are okay I would like to merge this to get packages out for the linux-aarch64 and linux-ppc64le platforms to move along a few other packages such as `psutils`

**Comment by jjhelmus** [comment]
Windows error is:
```
Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "C:\bld\mock_1550988135699\_h_env\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "C:\bld\mock_1550988135699\_h_env\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\bld\mock_1550988135699\_h_env\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\bld\mock_1550988135699\_h_env\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "C:\bld\mock_1550988135699\_h_env\lib\site-packages\pip\_internal\operations\prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\bld\mock_1550988135699\_h_env\lib\site-packages\pip\_internal\download.py", line 865, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\bld\mock_1550988135699\_h_env\lib\site-packages\pip\_internal\download.py", line 734, in unpack_file_url
    shutil.copytree(link_path, location, symlinks=True)
  File "C:\bld\mock_1550988135699\_h_env\lib\shutil.py", line 222, in copytree
    raise Error, errors
Error: [('C:\\bld\\mock_1550988135699\\work\\docs\\changelog.txt', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-lltojj\\docs\\changelog.txt', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\mock_1550988135699\\\\work\\\\docs\\\\changelog.txt'")]
```

**Comment by jakirkham** [comment]
Maybe it's because we are passing `--no-cache-dir` and setting `PIP_CACHE_DIR`. Could we try dropping `--no-cache-dir` and see if the issue is fixed?

**Comment by jakirkham** [comment]
Alright PR ( https://github.com/conda-forge/mock-feedstock/pull/14 ) should fix it. Left some notes in there about the problem and raised an issue upstream. Would like to get the build green here again. So if we could merge that first, that would be great. Looks like things have been failing here for a while. 😞

**Comment by jjhelmus** [comment]
Thanks @jakirkham.  I rebased this PR on top of #14.  Hoping for all green this time.

**Comment by jakirkham** [comment]
Thanks @jjhelmus :)

**Pull request merged**
