### PR TITLE
MNT: Re-rendered with conda-smithy 2.2.2

### PR DESCRIPTION
**Pull request by jakirkham**
Also add support for Python 3.6 and drop support for Python 3.4.

cc @pmlandwehr

### CODE REVIEW

**Comment by jakirkham** [comment]
I don't know if I will have time to pursue this further, but feel free to use this as a starting point, @pmlandwehr.

**Comment by jakirkham** [comment]
Yeah, so this is going to kind of be a disaster I think. The last time this built ok was with `setuptools` 20.7.0. There is no Python 3.6 package for that nor is there a recipe for that version at conda-forge (we started with 23.0.0). What is our reason for this version of `mock` again, @pmlandwehr?

**Comment by pmlandwehr** [comment]
`imapclient` requires it for the build. (ref. https://github.com/conda-forge/imapclient-feedstock/pull/6) This is probably silly, given that `mock` itself got folded into the main python distribution after `py32`, so if there's a better way around that...

**Comment by jakirkham** [comment]
I see. It appears this will be fixed in the next release. ( https://github.com/mjs/imapclient/pull/225 ) Maybe it is worth asking them whether they would be able to do a patch release or when there next minor release will be.

**Pull request closed without merging**
