### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
A feedstock I'd like to get working (https://github.com/conda-forge/apache-beam-feedstock) requires `mock<3.0.0` (which is quite annoying!).  Things are stuck because this old version hasn't been built with py>=3.8.

I don't want to bother anyone else about this so I'm hoping you'll be happy to just add me as a maintainer so I can take care of it.

**Comment by xylar** [comment]
I'm not bumping the build number because there's no need to re-upload the packages just for this.

**Comment by xylar** [comment]
@conda-forge/mock, are you okay with me becoming a maintainer?

**Comment by jakirkham** [comment]
Ofc! Welcome Xylar 😄

**Comment by xylar** [comment]
Thanks, @jakirkham!

**Pull request merged**
